# Generated by Django 3.2.6 on 2021-10-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211024_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
