# Generated by Django 3.2.8 on 2021-10-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='provider',
            field=models.CharField(default='email', max_length=20),
        ),
    ]
