# Generated by Django 3.2.8 on 2021-11-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.IntegerField(blank=True),
        ),
    ]
