# Generated by Django 3.2.8 on 2021-11-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211124_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.IntegerField(default='0000000000'),
        ),
    ]
