# Generated by Django 3.2.8 on 2021-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_myuser_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
