# Generated by Django 3.2.5 on 2021-10-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211022_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_payment',
            field=models.FloatField(default=0),
        ),
    ]
